### ISSUE TITLE
As a registered user, I want to change the mode in a lobby to ranked game if there are only registered users in the lobby in order to track the wins and losses and ranked score.

### ISSUE THREAD

**Issue by luis-tm** [sopra-fs22-group-16/sopra-fs22-group-16-client#75]
## Acceptance criteria
- [x] When creating a lobby, it is possible to change the mode of the game to ranked game with a button.
- [x] When playing with this mode, finishing a game updates the wins, losses and ranks of the players in the game.
- [x] When changing from unranked to ranked as a unregistered user I want to get informed that this is not possible.
- [x] When creating a ranked game as a unregistered user I want to get informed that this is not possible.
- [x] When changing from unranked to ranked with unregistered user(s) in the Lobby I want to get informed that this is not possible.
- [x] As a unregistered User I should not be able to join a ranked lobby

## Development tasks - Server
- [x] https://github.com/sopra-fs22-group-16/sopra-fs22-group-16-server/issues/308
- [x] https://github.com/sopra-fs22-group-16/sopra-fs22-group-16-server/issues/309
- [x] https://github.com/sopra-fs22-group-16/sopra-fs22-group-16-server/issues/310
- [x] https://github.com/sopra-fs22-group-16/sopra-fs22-group-16-server/issues/311
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#347
- [x] sopra-fs22-group-16/sopra-fs22-group-16-server#348

## Development tasks - Client
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#153
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#154
- [x] sopra-fs22-group-16/sopra-fs22-group-16-client#155
- [x] #176
